he4rt/react4noobs

docs/Iniciando com React/5-React Hooks.md
docs/README.md

Adiciona explicação básica sobre Hooks, e explica como utilizar o `useState` e `useEffect`.

feat(react-hooks): add useState and useEffect

---

README.md
docs/Iniciando com React/3-Componentizacao.md
docs/Iniciando com React/4-JSX.md

Corrigindo alguns typos que notei revisando o documento, e melhorando a leitura sobre os atributos React 😄

Fixing some typos and improving the text used

---

docs/Cliente REST/2-Axios.md

Adicionado explicação sobre o axios

feat(axios): explanation added

---

docs/README.md

BEEEEEEEEEEM bobo kkkkk Mas a URL atual está redirecionando p/ inglês, troquei p/ PT-BR

Alterando página do Node para PT-BR

---

docs/Iniciando com React/3-Componentizacao.md

Algumas melhorias que achei que poderiam aumentar a fluidez do texto sem impactar a semântica

:pencil: Pequenas melhorias em Componentização

---

docs/Iniciando com React/3-Componentizacao.md

Seguindo #37, a URL da imagem estava inacessível (403 - Access denied pela amazon). Troquei para uma nova que mantém a mesma semântica.

:bug: FIx img Dividindo interface em componentes

---

docs/README.md

Coisa boba, só que me incomoda muito KOPDWAKOPDKAWOP

Removendo espaços

---

docs/README.md
docs/Verificadores de Tipo/Typescript.md

Estou linkando o repo do Typescript aqui, quaisquer alterações necessárias é só me dar um toque =) 
re #22

Add Typescript Section

---

docs/Estilizacao/Preprocessadores CSS.md

Hey, tudo bem? adicionei um pequeno conteúdo sobre **funções** dentro do pré processador Sass! espero que seja útil =)

:pencil: feat: added sass functions into docs

---

docs/README.md
docs/Testes/2-testes-de-integracao.md

Como forma de agregar contribuição, decidi aplicar meus conhecimentos sobre testes no capítulo dedicado a este tema, mais especificamente sobre testes de integração
- adiciona uma página sobre teste de integração, onde conto o que é, o valor dos testes de integração em comparação aos testes unitários, ferramentas utilizadas neste tipo de teste e um exemplo simples.
- adiciona link no menu principal
- adiciona um gif animado que representa os testes unitários vs integrados
- [Write tests. Not too many. Mostly integration](https://kentcdodds.com/blog/write-tests)
- [Static vs Unit vs Integration vs E2E Testing for Frontend Apps](https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests)

:sparkles: adiciona capítulo sobre testes de integração

---

docs/Controle de estado/1-API-de-Contexto.md
docs/README.md

Conheci esse repositório recentemente e adorei a proposta. Parabéns pelo trabalho :heart:!
Já que recentemente usei a ContextAPI em um projeto, decidi escrever um capítulo sobre ela.
- [API de Contexto - Documentação do React](https://pt-br.reactjs.org/docs/context.html)

Adicionar capítulo sobre API de Contexto

---

docs/Bibliotecas de utilidade/2-Moment.md
docs/Cliente REST/2-Axios.md
docs/Controle de estado/1-API-de-Contexto.md
docs/Estilizacao/Preprocessadores CSS.md
docs/Ferramentas de build/1-npm.md
docs/Iniciando com React/3-Componentizacao.md
docs/Roteamento/1-React-Router.md
docs/Verificadores de Tipo/Typescript.md

Depois de algumas lidas e relidas nesse texto, percebi a necessidade de pequenas correções gramaticais (principalmente acentuação e typos).
Outras mudanças, trailing-spaces e new-line endings, foram feitas automaticamente pelo meu editor de texto. Achei válido mantê-las. 
Aproveitei também para escrever algumas sugestões de mudança de texto, que não são erros, só melhorias seguindo o meu próprio gosto. Se julgarem que é melhor reverter, escreve no review que eu reverto.

Correções gramaticais e algumas sugestões de mudança de texto

---

docs/README.md

Percebi que o link tava errado. Esse PR conserta o link no README.

Arrumar Link para API de contexto

---

docs/Cliente REST/2-Axios.md
docs/Controle de estado/1-API-de-Contexto.md
docs/Estilizacao/CSS-in-JS.md
docs/Iniciando com React/1-Introducao.md
docs/Iniciando com React/3-Componentizacao.md
docs/Iniciando com React/5-React Hooks.md
docs/Testes/2-testes-de-integracao.md

Correções de ortografia e acentuação.

Correções de palavras

---

docs/Cliente REST/1-Fetch.md

Olá!
Gostaria de contribuir com esse PR.
Grato por poder ajudar!
Closes #26

Adding Fetch to React4Noobs

---

docs/Iniciando com React/1-Introducao.md

I got this link from this list: https://github.com/he4rt/4noobs

Adding HTML4Noobs reference into introduction

---

docs/Iniciando com React/4-Componentizacao.md
docs/Iniciando com React/4.1-FormasDeDeclarar.md
docs/Iniciando com React/4.2-Propriedades.md
docs/README.md

Os novos tópicos buscam ensinar a declarar componentes(tanto funcionais quanto em classes) e mostrar como utilizar as props de um componente.

Tópicos: Formas de Declarar componentes  e Propriedadades

---

docs/Cliente GraphQL/1-Conceito.md
docs/README.md

Decidi já mandar o PR com a contribuição para não atrapalhar outros usuários que queira contribuir e irei continuar com a contribuição no Apollo.
Obs.: Coloquei também uma nova seção para aprofundar mais no conteúdo de bibliotecas.

add: graphql concept

---

docs/Estilizacao/1.Preprocessadores CSS.md
docs/Estilizacao/3.0.CSS-in-JS.md
docs/Estilizacao/3.1-styled-components.md
docs/README.md

Refactoring the part of CSS in JS because the practical example of styled components left a document too long, going beyond the desired

Refactoring the CSS in JS part

---

docs/Iniciando com React/8-React Hooks.md

Resolvido problema de uso inadequado do hook useState na parte de alteração de estado, chamando o próprio estado invés do seu anterior.

fix: solve a problem in useState hook

---

docs/Iniciando com React/8-React Hooks.md

Adicionado o hook de useMemo na lista de hooks que estão disponíveis.

feat: adds useMemo and useCallback hook

---

docs/Iniciando com React/8-React Hooks.md

fix: useRef hook description

---

docs/Iniciando com React/4.1-FormasDeDeclarar.md
docs/Iniciando com React/4.2-Propriedades.md
docs/Iniciando com React/5-Estados.md

Reescrevi algumas coisas, mas enviei no discord um pedido de amizade para podermos conversar melhor de como proceder.

Reescrita de algumas partes

---

docs/Iniciando com React/8.1-useState.md

Adicionado o detalhe de que a função de alterar estado pode receber uma função e um exemplo extra um pouco mais complexo.
Substitui a #79 porque eu fiz caca quando abri :rofl:

React Hooks: useState

---

docs/Iniciando com React/Refs.md
docs/Iniciando com React/Renderizacao-condicional.md
docs/README.md

- Adicionado artigo sobre Renderização Condicional
close #111

Add artigo sobre Renderização Condicional

---

docs/Controle de estado/3-Zustand.md

Segue minha humilde contribuição, qualquer dica ou recomendação é bem vinda 😃

Controle de estado: Zustand

---

docs/Iniciando com React/9-React Error Boundaries.md

Applying these suggestions: https://github.com/he4rt/react4noobs/pull/137#discussion_r1447427077

feat: adjust texts error boundaries
